# Generated by Django 4.2.4 on 2023-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0037_alter_staff_name_alter_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[(0, "Team Lead"), (1, "Member")], default=1, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="staffsection",
            name="section_name",
            field=models.CharField(
                choices=[
                    (1, "Executive"),
                    (2, "Scientific"),
                    (3, "Technical"),
                    (4, "Graphic"),
                    (5, "Marketing"),
                ],
                default=1,
                max_length=100,
            ),
        ),
    ]
