# Generated by Django 4.2.4 on 2023-11-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend_api', '0040_staff_section_name_delete_staffsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='authority',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ref_id',
        ),
        migrations.DeleteModel(
            name='NewPayment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='track_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
