# Generated by Django 4.2.4 on 2023-11-18 19:44

from django.db import migrations, models
import django.db.models.deletion


def create_workshop_relations_relations(apps, schema_editor):
    User = apps.get_model('backend_api', 'User')
    WorkshopRegistration = apps.get_model('backend_api', 'WorkshopRegistration')
    for user in User.objects.all():
        for workshop in user.registered_workshops.all():
            WorkshopRegistration(
                workshop=workshop,
                user=user,
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend_api', '0041_rename_total_price_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'خریداری شده')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.user')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'user')},
            },
        ),
        migrations.RunPython(
            code=create_workshop_relations_relations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_workshops',
        ),
        migrations.AddField(
            model_name='user',
            name='registered_workshops',
            field=models.ManyToManyField(blank=True, through='backend_api.WorkshopRegistration',
                                         to='backend_api.workshop'),
        ),
    ]
