# Generated by Django 4.2.4 on 2023-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0043_alter_workshopregistration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='workplace_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
