export default function useMyAccount() {
  const talks = [
    {
      id: 1,
      name: 'Discriminative Feature Learning and Face Recognition',
      desc: 'پیش‌نیازهای کارگاه: \r\nKeras, Tensorflow, Convnet',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-31T18:00:00Z',
      presenters: [],
      cost: 50000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 30,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 2,
      name: 'A tutorial on evaluating generative models',
      desc: 'A tutorial on evaluating generative models',
      year: 2021,
      level: 'Elementary',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-31T18:00:00Z',
      presenters: [10],
      cost: 50000,
      hasProject: false,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 50,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 3,
      name: 'on the privacy Risks of algorithmic fairness',
      desc: 'on the privacy Risks of algorithmic fairness',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [11],
      cost: 12000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 20,
      isFull: true,
      addToCalendarLink: 'https://google.com',
    },
  ];

  const workshops = [
    {
      id: 4,
      name: 'Foundations of Data Augmentation',
      desc: 'Foundations of Data Augmentation',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [13],
      cost: 50000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 50,
      isFull: true,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 5,
      name: 'Representation Learning Without Labels',
      desc: 'Representation Learning Without Labels',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [16],
      cost: 20000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 20,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 6,
      name: '3D CNNs with Adaptive Temporal Feature Resolutions',
      desc: '3D CNNs with Adaptive Temporal Feature Resolutions',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [14],
      cost: 50000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 50,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 7,
      name: 'Learning Representations on Graphs',
      desc: 'Learning Representations on Graphs',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [17],
      cost: 50000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 50,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
    {
      id: 8,
      name: 'An Introduction to Autonomous Vehicles',
      desc: 'An Introduction to Autonomous Vehicles',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [18],
      cost: 50000,
      hasProject: true,
      prerequisites: 'Basic knowledge of machine learning',
      syllabus: 'GANs in different type of problems - Various types of GANs - Coding',
      capacity: 50,
      isFull: false,
      addToCalendarLink: 'https://google.com',
    },
  ];

  const cart = [
    {
      id: 4,
      name: 'Foundations of Data Augmentation',
      desc: 'Foundations of Data Augmentation',
      year: 2021,
      level: 'NOT_ASSIGNED',
      start_date: '2021-08-27T06:00:00Z',
      end_date: '2021-08-30T18:00:00Z',
      presenters: [13],
      cost: 120000,
    },
  ];

  return {
    talks,
    workshops,
    cart,
  };
}
