# Generated by Django 4.2.4 on 2023-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0035_remove_staff_entrance_remove_staff_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(
                choices=[("TL", "Team Lead"), ("MB", "Member")],
                default="Human",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(default="MB", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffsection",
            name="section_name",
            field=models.CharField(
                choices=[
                    ("EXC", "Executive"),
                    ("SCI", "Scientific"),
                    ("TCH", "Technical"),
                    ("GRP", "Graphic"),
                    ("MRK", "Marketing"),
                ],
                default="EX",
                max_length=100,
            ),
        ),
    ]
