# Generated by Django 4.2.4 on 2023-11-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0036_alter_staff_name_alter_staff_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(default="Human", max_length=100),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[("TL", "Team Lead"), ("MB", "Member")],
                default="MB",
                max_length=100,
            ),
        ),
    ]
