# Generated by Django 4.2.4 on 2023-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0044_presenter_workplace_logo_teacher_workplace_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="workplace_logo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
