# Generated by Django 4.2.4 on 2023-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0045_teacher_workplace_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="workplace",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
