# Generated by Django 4.2.4 on 2023-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0046_teacher_workplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_done',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting payment'), (1, 'Payment confirmed'), (2, 'Payment rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
