# Generated by Django 4.2.4 on 2023-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0047_remove_payment_is_done_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
