# Generated by Django 4.2.4 on 2023-11-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0049_alter_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="has_project",
            field=models.BooleanField(default=False),
        ),
    ]
