# Generated by Django 4.2.4 on 2023-11-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0050_presentation_has_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshop",
            name="add_to_calendar_link",
        ),
    ]
