# Generated by Django 4.2.4 on 2023-11-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0051_remove_workshop_add_to_calendar_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[("Team Lead", "TL"), ("Member", "MB"), ("Coordinator", "CR")],
                default="Executive",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="section_name",
            field=models.CharField(
                choices=[
                    ("Coordination", "CR"),
                    ("Executive", "EXC"),
                    ("Scientific", "SCI"),
                    ("Technical", "TCH"),
                    ("Graphic", "GRP"),
                    ("Marketing", "MRK"),
                ],
                default="Member",
                max_length=100,
            ),
        ),
    ]
