# Generated by Django 4.2.4 on 2023-12-03 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0053_alter_staff_role_alter_staff_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='BTusxOmw', max_length=8, unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.discount'),
        ),
    ]
