# Generated by Django 4.2.4 on 2023-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0054_discount_payment_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                default="gZOMBJ8W9Q0r4ln8odqIoAWOniIXQzmo", max_length=32, unique=True
            ),
        ),
    ]
