# Generated by Django 4.2.4 on 2023-12-05 21:26

from django.db import migrations

from utils.random import create_random_string


def make_passwords_random(apps, schema_editor):
    WorkshopRegistration = apps.get_model('backend_api', 'WorkshopRegistration')
    PresentationParticipation = apps.get_model('backend_api', 'PresentationParticipation')
    for registration in WorkshopRegistration.objects.all():
        registration.password = create_random_string(16)
        registration.save()
    for participation in PresentationParticipation.objects.all():
        participation.password = create_random_string(16)
        participation.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend_api', '0056_presentationparticipation_password_and_more'),
    ]

    operations = [
        migrations.RunPython(make_passwords_random)
    ]
