# Generated by Django 4.2.4 on 2023-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0057_make_passwords_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='recorded_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='recorded_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
