# Generated by Django 4.2.4 on 2024-01-11 13:15

from django.db import migrations, models
import utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0058_presentation_recorded_link_workshop_recorded_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default=utils.random.random_discount_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='presentationparticipation',
            name='password',
            field=models.CharField(default=utils.random.random_password, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='password',
            field=models.CharField(default=utils.random.random_password, max_length=255),
        ),
    ]
