# Generated by Django 4.2.4 on 2024-01-11 13:39

from django.db import migrations, models
import utils.image_uploader
import uuid


def set_default_uuid(apps, schema_editor):
    workshop_participation = apps.get_model('backend_api', 'workshopregistration')
    presentation_participation = apps.get_model('backend_api', 'presentationparticipation')
    for instance in presentation_participation.objects.filter(certificate_uuid__isnull=True):
        instance.certificate_uuid = uuid.uuid4()
        instance.save()
    for instance in workshop_participation.objects.filter(certificate_uuid__isnull=True):
        instance.certificate_uuid = uuid.uuid4()
        instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend_api', '0059_alter_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationparticipation',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to=utils.image_uploader.update_certificate_filename),
        ),
        migrations.AddField(
            model_name='presentationparticipation',
            name='certificate_uuid',
            field=models.UUIDField(default=None, editable=False, unique=False, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to=utils.image_uploader.update_certificate_filename),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='certificate_uuid',
            field=models.UUIDField(default=None, editable=False, unique=False, null=True),
        ),
        migrations.RunPython(set_default_uuid),
        migrations.AlterField('presentationparticipation', 'certificate_uuid',
                              models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)),
        migrations.AlterField('workshopregistration', 'certificate_uuid',
                              models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)),
    ]
