# Generated by Django 4.2.4 on 2024-01-11 13:56

from django.db import migrations, models
import utils.image_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0060_presentationparticipation_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationparticipation',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to=utils.image_uploader.update_certificate_filename),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to=utils.image_uploader.update_certificate_filename),
        ),
    ]
