# Generated by Django 4.2.4 on 2024-01-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0061_alter_presentationparticipation_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationparticipation',
            name='certificate_uuid',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='certificate_uuid',
        ),
    ]
