# Generated by Django 4.2.4 on 2025-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0062_remove_presentationparticipation_certificate_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='presenters',
        ),
        migrations.AddField(
            model_name='presentation',
            name='teachers',
            field=models.ManyToManyField(to='backend_api.teacher'),
        ),
    ]
