# Generated by Django 4.2.4 on 2025-12-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0063_remove_presentation_presenters_presentation_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='teachers',
            new_name='presenters',
        ),
    ]
