name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.20.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker images
        run: docker compose build --push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          overwrite: true
          source: "docker-compose.yml,deployment"
          target: /home/${{ vars.VM_USERNAME }}/AAISS-2023

      - name: Deploy to the VM
        uses: appleboy/ssh-action@master
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
          ZIFY_AUTH: ${{ secrets.ZIFY_AUTH }}
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SECRET_KEY,EMAIL_HOST_PASSWORD,ZIFY_AUTH
          script: |
            docker compose -f AAISS-2023/docker-compose.yml up -d --force-recreate --no-build

      - name: Cleanup docker images
        uses: appleboy/ssh-action@master
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker image prune -af
