name: display secrets

on:
  workflow_dispatch: 

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ZIFY_AUTH: ${{ secrets.ZIFY_AUTH }}
        run: |
          echo DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN >> secrets.txt
          echo DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME >> secrets.txt
          echo EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD >> secrets.txt
          echo SECRET_KEY: $SECRET_KEY >> secrets.txt
          echo SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
